import { Toaster } from "@/shared/components/ui/sonner";
import { shabnamFont } from "@/shared/lib/fonts";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={`h-full antialiased ${shabnamFont.className}`}
    >
      <body className="min-h-full flex flex-col">
        <Toaster dir="rtl" richColors position="top-right" />
        <main>{children}</main>
      </body>
    </html>
  );
}
